# This is a dev docker-compose file which exports your wiki on localhost:8050
services:
  lhs:
    build: .
    environment:
      URL_PREFIX:
    volumes:
      - /var/lib/wiki/lhs/images:/images
      - /var/lib/wiki/lhs/config:/config
    ports:
      - 8050:80
    links:
      - memcached:memcached
    restart: unless-stopped
    logging:
      driver: journald

  memcached:
    image: 'memcached:1.6.29'
    restart: unless-stopped
    command: memcached -m 128
