# This is a dev docker-compose file which exports your wiki on localhost:8050

services:
  nginx:
    build: nginx
    ports:
      - 0.0.0.0:8050:80
    restart: unless-stopped

  wiki:
    build: .
    environment:
      URL_PREFIX:
    volumes:
      - ./dev/files/images:/images
      - ./dev/files/config:/config
      - ./dev/files/log:/var/log      
      - ./dev/files/log/nginx:/var/log/nginx
    links:
      - memcached:memcached
      - db:db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: "postgres:16.1-alpine"
    environment:
      - POSTGRES_DB=hackspacewiki
      - POSTGRES_USER=hackspacewiki
      - POSTGRES_PASSWORD=wiki
    ports:
      - 0.0.0.0:5482:5432

  memcached:
    image: 'memcached:1.6.29'
    restart: unless-stopped
    command: memcached -m 128
